### ISSUE TITLE
Fishing; add note to wiki for fishing to re-run init.bat

### ISSUE THREAD

**Issue by Hunteil** [ilpersi/BHBot#133]
Simple. Just add a note to the wiki to re-run the init.bat steps for it to recognize the fishing .jar file.

**Comment by ilpersi** [comment]
Actually you don't need to re-run init.bat to have the bot recognize the fishing jar file.

You just have to
* put the jar in the BHBot path
* add the `f` letter to the `activitiesEnabled` setting
* restart the bot or simple issue a `reload` command if the bot is already running.

Keep in mind that the bot will try to fish every six hours.

**Comment by Hunteil** [comment]
It was the 6 hour thing. But re-running the init.bat reset the 6 hour clock so I thought it fixed it lol.
Anyway to change the setting to a different time other than 6 hours? Or should we just run it with the stand alone fish bot? (haven't used it yet)

**Comment by ilpersi** [comment]
To reset timers, you just have to stop the bot and start it again or use the `readouts` command to reset the timers.

Please note: in the currently published release the `readouts` command does not reset fishing timers. This is fixed in commit a175c40dc953731de4bcec3f5cc29ed2154464fc and it will be included in the next release.

**Comment by ilpersi** [comment]
@Hunteil The fix was included in v43 so I am closing this. Please open a new issue if you still need help.
