### ISSUE TITLE
Rogue bot?

### ISSUE THREAD

**Issue by Hunteil** [ilpersi/BHBot#159]
![fishing rogue](https://user-images.githubusercontent.com/8192771/80822329-790ec880-8ba8-11ea-9608-002d1199cf8a.PNG)
So the bot crashed and I used crt+c to force stop it....

So I went to explore the new fishing thing and started to manually fish...after 5 attempts of doing myself... the fishing bot activated on it's own and I have no idea how it's doing it lol.

Not that I'm complaining b/c I've been meaning to turn the fishing bot on alone but I didn't know how to do it.

After a dozen fishing it stopped. So I clicked fish start again and it took off again lol. This is entertaining.... and possibly bad b/c there's no way to turn it off over than to reboot lol this is hilarious. Nothing is changing in the command window.

It seems to time out every now and then. Otherwise I'd let it go forever but... I guess I gotta terminate it.

~~On this note... if we could use the pause command to pause the bot... I wouldn't be against it fishing for me like this lol. Maybe add parameter to settings.ini to allow this? But then again maybe better off using the fishing bot.~~ <- As far as running fishing myself. I now see it's very easy to trigger myself. I'll just use the command to run it and adjust the quantity of baits.

**Comment by Hunteil** [comment]
As far as running fishing myself. I now see it's very easy to trigger myself. I'll just use the command to run it and adjust the quantity of baits.

**Comment by ilpersi** [comment]
I don't understand what the issue is. That being said:

- to investigate I need full logs (the screenshot is cropped)
- the right way to stop the bot is not ctrl+c, but to issue a `stop` command in the console
- to work correctly the fishing integration requires the browser to be the foreground window and to have full control of the inputs (you should not interact with the PC while it is running)
- the fishing integration is clunky and it works spawning a process, so when you ctrl+c the main process it may be possible that the unexpected things happen

I personally do not use it as on virtual machines it does not work, I know that @Fortigate is using it successfully so maybe he can give you better advice.

My best advice is to run the standard version of the bot manually every now and then.

**Comment by Hunteil** [comment]
Okay. Let's just ignore this then.
btw I only used crtl+c b/c I couldn't type. (frozen)

I just thought it was funny to share b/c I've never seen the fishing bot react so freely. Before it would stop immediately and give up trying if you accidentally moved the mouse. In this scenario it didn't mind it.
