### ISSUE TITLE
Question: download jar

### ISSUE THREAD

**Issue by Hakatitla** [ilpersi/BHBot#164]
In releases add please link to jar file. For those who are using jar and already have java 11

**Comment by ilpersi** [comment]
The jar file is packed within the zip release.
I recommend you to review the [Java Steps](https://github.com/ilpersi/BHBot/wiki#java-steps) of the installation guide in case of doubts.

**Comment by Hakatitla** [comment]
Yes, but why to download 50mb zip file id the jar has 13mb

**Comment by ilpersi** [comment]
New versions are released about once a month (even less) and honestly, considering this frequency, I prefer not to upload the same thing twice.

In my opinion it would also be confusing for non techie user to have two files instead of a single nicely packed zip with an exe inside.

If you really want to reduce the download size, you may consider compiling from source that way you can also get latest fixes and updates.
