### ISSUE TITLE
Bot hangs on "not enough resources" dialog

### ISSUE THREAD

**Issue by ImVeryVeryStupid** [ilpersi/BHBot#177]
I seem to be getting a lot of the glitches in game where the game doesn't update your resources correctly after you've spent them i.e. if I have 6 raid shards and run one raid the game will still show 6 raid shards.
After doing all the resources bot will still see resources to be left and will run one more but will not detect "not enough resources" dialog.
I suggest implementing a check for this dialog so the bot won't hang there and just sit doing nothing.

**Comment by ilpersi** [comment]
I've seen this happening, but never with raids.

When this happened the bot should have gone in timeout and also saved a screenshot. 

To implement this feature I need:
-  the logs of when it happened (check for the correct day in the `/logs` folder)
- the screenshot of the pop-up (you can not take it, the bot automatically takes it and places it in the `/screenshots/error` path)

Otherwise, I am not able to understand when the "not enough resources" pop-up happened.

**Comment by ilpersi** [comment]
No feedback in more than one month. Closing this.
